name: Build'n'deploy workflow

on:
  workflow_dispatch:

jobs:
  build_n_deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout the source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0

      - name: Setup Java Build Environment
        uses: ./.github/actions/setup-java-build-env
        with:
          gh_user: ${{ secrets.GIT_USER }}
          gh_token: ${{ secrets.GIT_PAT }}

      - name: Build and deploy
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ${{ runner.temp }}/maven/bin/mvn --batch-mode deploy -Pvalidate -s ${{ runner.temp }}/settings.xml --no-transfer-progress

      - name: Build and deploy site
        run: ${{ runner.temp }}/maven/bin/mvn --batch-mode site -s ${{ runner.temp }}/settings.xml --no-transfer-progress
