name: Pull request validation

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-validation:
    runs-on: ubuntu-22.04

    steps:
      - name: PR validation
        uses: pagopa/mil-actions/pr-validation@main
        with:
          gh_user: ${{ secrets.GIT_USER }}
          gh_token: ${{ secrets.GIT_PAT }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
