name: Pull request validation

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: PR title validation
        uses: amannn/action-semantic-pull-request@c3cd5d1ea3580753008872425915e343e351ab54
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            docs
            refactor
            chore
            fix
            feat
            breaking
          requireScope: false
          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            doesn't match the configured pattern. Please ensure that the subject
            starts with an uppercase character.
          wip: false

      - name: Checkout the repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Download JDK and verify its hash
        run: |
          echo "e9458b38e97358850902c2936a1bb5f35f6cffc59da9fcd28c63eab8dbbfbc3b  $RUNNER_TEMP/jdk_setup.tar.gz" >> $RUNNER_TEMP/jdk_setup.sha256
          curl -L "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.7%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz" -o "$RUNNER_TEMP/jdk_setup.tar.gz"
          sha256sum --check --status "$RUNNER_TEMP/jdk_setup.sha256"

      - name: Setup JDK 
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          distribution: "jdkfile"
          jdkFile: "$RUNNER_TEMP/jdk_setup.tar.gz"
          java-version: "17"

      - name: Download Maven and verify its hash
        run: |
          echo "809ef3220c6d179195c06c324cb9a6d34d8ecba566c5cfd8eb83167bc034117d  $RUNNER_TEMP/maven_setup.tar.gz" >> $RUNNER_TEMP/maven_setup.sha256
          curl -L "https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz" -o "$RUNNER_TEMP/maven_setup.tar.gz"
          sha256sum --check --status "$RUNNER_TEMP/maven_setup.sha256"

      - name: Setup Maven
        run: |
          mkdir $RUNNER_TEMP/maven
          tar -xvf $RUNNER_TEMP/maven_setup.tar.gz -C $RUNNER_TEMP/maven --strip-components=1
          ls $RUNNER_TEMP/maven
          echo "<settings><servers><server><id>github</id><username>${{ secrets.GIT_USER }}</username><password>${{ secrets.GIT_PAT }}</password></server></servers></settings>" >> $RUNNER_TEMP/settings.xml

      - name: Execute unit-testing
        run: |
          echo ${{ env.PATH }}
          mvn -v
          mvn clean test -s $RUNNER_TEMP/settings.xml --no-transfer-progress